# frozen_string_literal: true

source "https://rubygems.org"

ruby '3.2.2'
gem 'fastlane', '2.214.0'
gem 'slather', '~>2.7.4'
gem 'gibberish'
gem 'xcode-install'
gem 'dotenv'
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
# gem "rails"

gem "danger", "~> 9.3"
