import SwiftUI

public extension Image {

    // Icons
    static let addCircleIcon = Image("ic-add-circle", bundle: .module)
    static let sliderCircleIcon = Image("ic-slider-circle", bundle: .module)
    static let addSquareIcon = Image("ic-add-square", bundle: .module)
    static let addSingleIcon = Image("ic-add-single", bundle: .module)
    static let additionalCoverageSectionIcon = Image("ic-additional-coverage-section", bundle: .module)
    static let additionalPartiesSectionIcon = Image("ic-additional-parties-section", bundle: .module)
    static let addressIcon = Image("ic-address", bundle: .module)
    static let cameraIcon = Image("ic-camera", bundle: .module)
    static let checkIcon = Image("ic-check", bundle: .module)
    static let arrowUpIcon = Image("ic-chevron-up", bundle: .module)
    static let arrowDownIcon = Image("ic-chevron-down", bundle: .module)
    static let backIcon = Image("ic-chevron-left", bundle: .module)
    static let editAdditionalCoverageIcon = Image("ic-edit-additional-coverage", bundle: .module)
    static let creditCardIcon = Image("ic-credit-card", bundle: .module)
    static let coveredIcon = Image("ic-covered", bundle: .module)
    static let editPolicyIcon = Image("ic-edit-policy", bundle: .module)
    static let rentersInsuranceSectionIcon = Image("ic-renters-insurance-section", bundle: .module)
    static let scheduledItemsSectionIcon = Image("ic-scheduled-items-section", bundle: .module)
    static let closeIcon = Image("ic-close", bundle: .module)
    static let deleteIcon = Image("ic-delete", bundle: .module)
    static let delete2Icon = Image("ic-delete-2", bundle: .module)
    static let editIcon = Image("ic-edit", bundle: .module)
    static let uploadIcon = Image("ic-upload", bundle: .module)
    static let javierRentersIcon = Image("ic-javier-renters", bundle: .module)
    static let javierPinkRentersIcon = Image("ic-javier-renters-pink", bundle: .module)
    static let houseIcon = Image("ic-house", bundle: .module)
    static let houseSectionIcon = Image("ic-house-section", bundle: .module)
    static let starDefaultIcon = Image("ic-star-default", bundle: .module)
    static let galleryIcon = Image("ic-gallery", bundle: .module)
    static let fileIcon = Image("ic-file", bundle: .module)
    static let sendIcon = Image("ic-send", bundle: .module)
    static let informationIcon = Image("ic-information", bundle: .module)
    static let informationFilledIcon = Image("ic-information-fill", bundle: .module)
    static let rentersTabItem = Image("ic-tab-renters-selected", bundle: .module)
    static let paymentSectionIcon = Image("ic-payment-section", bundle: .module)
    static let paymentIcon = Image("ic-payment", bundle: .module)
    static let cancelIcon = Image("ic-cancel", bundle: .module)
    static let faqIcon = Image("ic-faq", bundle: .module)
    static let messageIcon = Image("ic-message", bundle: .module)
    static let phoneIcon = Image("ic-phone", bundle: .module)
    static let emailIcon = Image("ic-email", bundle: .module)
    static let videoPlayIcon = Image("ic-video-play", bundle: .module)
    static let theftIcon = Image("ic-theft", bundle: .module)
    static let fireIcon = Image("ic-fire", bundle: .module)
    static let smokeIcon = Image("ic-smoke", bundle: .module)
    static let hailIcon = Image("ic-hail", bundle: .module)
    static let lightningIcon = Image("ic-lightning", bundle: .module)
    static let windstormIcon = Image("ic-windstorm", bundle: .module)
    static let vandalismIcon = Image("ic-vandalism", bundle: .module)
    static let explosionIcon = Image("ic-explosion", bundle: .module)
    static let comunicationIcon = Image("ic-comunication", bundle: .module)
    static let whatsappIcon = Image("ic-whatsapp", bundle: .module)
    static let copy = Image("ic-copy", bundle: .module)
    static let videoCall = Image("ic-video-call", bundle: .module)

    static let iconStatusSingleFamily = Image("ic-status-single-family", bundle: .module)
    static let iconStatusMultiFamily = Image("ic-status-multi-family", bundle: .module)
    static let iconStatusStudent = Image("ic-status-student", bundle: .module)
    static let iconStatusTownhouse = Image("ic-status-townhouse", bundle: .module)
    static let iconStatusApartment = Image("ic-status-apartment", bundle: .module)
    
    static let replacementCostIcon = Image("ic-replacement-cost", bundle: .module)
    static let waterSewerBackupIcon = Image("ic-water-sewer", bundle: .module)
    static let fraudProtectionIcon = Image("ic-fraud-protection", bundle: .module)
    
    static let airvetStepOne = Image("ic-step-one-airvet", bundle: .module)
    static let airvetStepTwo = Image("ic-step-two-airvet", bundle: .module)
    static let airvetStepThree = Image("ic-step-three-airvet", bundle: .module)

    static let stepCompleted = Image("ic-step-completed", bundle: .module)
    static let stepAlert = Image("ic-step-alert", bundle: .module)
    static let share = Image("ic-share", bundle: .module)
    static let deniedFilled = Image("ic-denied-filled", bundle: .module)

    // Images
    static let warningImage = Image("image-warning", bundle: .module)
    static let petUpsellingHeader = Image("pet_upselling", bundle: .module)
    static let petUpsellingBackgrounded = Image("pet_upselling_backgrounded", bundle: .module)
    static let rentersUpsellingHeader = Image("renters_upselling", bundle: .module)
    static let rentersUpsellingBackgrounded = Image("renters_upselling_backgrounded", bundle: .module)
    static let imageThumbDefault = Image("picture-thumbnail-default", bundle: .module)
    static let statusSingleFamily = Image("status-single-family", bundle: .module)
    static let statusMultiFamily = Image("status-multi-family", bundle: .module)
    static let statusStudent = Image("status-student", bundle: .module)
    static let statusTownhouse = Image("status-townhouse", bundle: .module)
    static let statusApartment = Image("status-apartment", bundle: .module)
    static let guitarImage = Image("image-guitar", bundle: .module)
    static let searchImage = Image("image-search", bundle: .module)
    static let loadingImage = Image("image-loading", bundle: .module)
    static let donationImage = Image("image-donation", bundle: .module)
    static let errorImage = Image("image-error", bundle: .module)
    static let requestFailedImage = Image("request-failed", bundle: .module)
    static let renterFaqImage = Image("renters-faq-image", bundle: .module)
    static let feedback1 = Image("feedback-1", bundle: .module)
    static let feedback2 = Image("feedback-2", bundle: .module)
    static let feedback3 = Image("feedback-3", bundle: .module)
    static let feedback4 = Image("feedback-4", bundle: .module)
    static let feedback5 = Image("feedback-5", bundle: .module)
    static let homeFaqImage = Image("home-faq-image", bundle: .module)
    static let airvetImage = Image("image-airvet", bundle: .module)
    static let airvetImageNoBackground = Image("image-airvet-no-background", bundle: .module)
    static let defaultCatImage = Image("defaultPicture-cat", bundle: .module)
    static let defaultDogImage = Image("defaultPicture-dog", bundle: .module)

    // Schedule Item Categories
    static let categoryDesign = Image("item-category-designer", bundle: .module)
    static let categoryElectricScooter = Image("item-category-electricScooter", bundle: .module)
    static let categoryElectronics = Image("item-category-electronics", bundle: .module)
    static let categoryFineArt = Image("item-category-fineart", bundle: .module)
    static let categoryHighValue = Image("item-category-highValueItem", bundle: .module)
    static let categoryHomeVideo = Image("item-category-homeVideo", bundle: .module)
    static let categoryJewelry = Image("item-category-jewelry", bundle: .module)
    static let categoryMusical = Image("item-category-musical", bundle: .module)
    static let categoryRareBooks = Image("item-category-rareBooks", bundle: .module)
    static let categorySport = Image("item-category-sporting", bundle: .module)
}
